<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD 추가 -->
<!DOCTYPE memberList 
[
<!ELEMENT memberList (memberInfo+)>
<!ELEMENT memberInfo (name, telephone, curriculumn?, zipCode, addr)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT curriculumn (sub+)>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT zipCode (#PCDATA)>
<!ELEMENT addr (#PCDATA)>
<!ATTLIST memberInfo mid CDATA #REQUIRED>
]>

<!-- #REQUIRED : 이 속성은 반드시 명시되어야 함  -->
<!-- #IMPLIED : 이 속성은 명시되기도 하고, 명시되지 않기도 함  -->
<!-- #FIXED : 이 속성은 특정ㄱ밧으로 고정되어 사용됨 -->

<memberList>
	<memberInfo mid="1">
		<name>노은하</name>
		<telephone><![CDATA[010-1234-4567]]></telephone>
		<curriculumn>
			<sub>JAVA SE</sub>
			<sub>ORACLE</sub>
			<sub><![CDATA[Servlet&JSP]]></sub>
		</curriculumn>
		<zipCode>01234</zipCode>
		<addr>서울시 마포구 월드컵북로 150</addr>
	</memberInfo>
	
	<memberInfo mid="2">
		<name>김민지</name>
		<telephone><![CDATA[010-9987-8876]]></telephone>
		<zipCode>01285</zipCode>
		<addr>서울시 은평구 통일로 20</addr>
	</memberInfo>	
	
</memberList>
